Traceback (most recent call last):
  File "C:\Python\Miniconda3\envs\graffiti_book\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python\Miniconda3\envs\graffiti_book\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Miniconda3\envs\graffiti_book\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Miniconda3\envs\graffiti_book\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python\Miniconda3\envs\graffiti_book\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Python\Miniconda3\envs\graffiti_book\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python\Miniconda3\envs\graffiti_book\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# add markers for each graffiti to our markercluster
for indx, row in df.iterrows():
    # create marker
    folium.Marker(location = [ row.lat, row.long ],                            # location of each graffiti
                     popup = row.type,                                         # identify the popup with each type
                      icon = folium.Icon(color = type2color[row.type], icon='pencil') # create an icon
                  ).add_to(marker_cluster)

------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[34], line 6[0m
[0;32m      1[0m [38;5;66;03m# add markers for each graffiti to our markercluster[39;00m
[0;32m      2[0m [38;5;28;01mfor[39;00m indx, row [38;5;129;01min[39;00m df[38;5;241m.[39miterrows():
[0;32m      3[0m     [38;5;66;03m# create marker[39;00m
[0;32m      4[0m     folium[38;5;241m.[39mMarker(location [38;5;241m=[39m [ row[38;5;241m.[39mlat, row[38;5;241m.[39mlong ],                            [38;5;66;03m# location of each graffiti[39;00m
[0;32m      5[0m                      popup [38;5;241m=[39m row[38;5;241m.[39mtype,                                         [38;5;66;03m# identify the popup with each type[39;00m
[1;32m----> 6[0m                       icon [38;5;241m=[39m folium[38;5;241m.[39mIcon(color [38;5;241m=[39m [43mtype2color[49m[row[38;5;241m.[39mtype], icon[38;5;241m=[39m[38;5;124m'[39m[38;5;124mpencil[39m[38;5;124m'[39m) [38;5;66;03m# create an icon[39;00m
[0;32m      7[0m                   )[38;5;241m.[39madd_to(marker_cluster)

[1;31mNameError[0m: name 'type2color' is not defined

